import { readFile, writeFile } from 'node:fs/promises';
const core = await readFile(new URL('cleaner-core.js', import.meta.url), 'utf8');
const adapter = await readFile(new URL('content.js', import.meta.url), 'utf8');
const bundle = `/* Generated by node build.mjs. Paste on Watch Later. Stop with WatchLaterCleaner.stop(). */\n${core}\n${adapter}\nWatchLaterCleaner.start(0);\n`;
await writeFile(new URL('removeWatchLater.js', import.meta.url), bundle);
