/* Generated by node build.mjs. Paste on Watch Later to remove EVERYTHING (explicit delete-all). Stop with WatchLaterCleaner.stop(). */
/* Shared, browser-independent cleaning engine. No page-model mutations. */
(() => {
  'use strict';
  // Safe default: only mostly-watched videos are removed unless the user chooses
  // otherwise. 0% (delete everything) is never implicit; it needs confirmation.
  const DEFAULT_THRESHOLD = 90;
  const percent = value => Math.max(0, Math.min(100, Math.round(Number(value) || 0)));
  const watchedPercent = value => {
    const number = Number(typeof value === 'string' ? value.trim().replace(/%$/, '') : value);
    return Number.isFinite(number) ? Math.max(0, Math.min(100, number)) : 0;
  };
  const isWatchLater = value => {
    try {
      const url = new URL(value);
      return ['https:', 'http:'].includes(url.protocol)
        && ['www.youtube.com', 'youtube.com'].includes(url.hostname)
        && url.pathname === '/playlist' && url.searchParams.get('list') === 'WL';
    } catch (_) { return false; }
  };
  class Failure extends Error {
    constructor(message, code = 'api', status = 0) { super(message); this.code = code; this.status = status; }
  }
  const cancelled = () => new Failure('Stopped.', 'cancelled');
  function check(signal) { if (signal?.aborted) throw cancelled(); }
  function delay(ms, signal) {
    check(signal);
    return new Promise((resolve, reject) => {
      const abort = () => { clearTimeout(timer); reject(cancelled()); };
      const timer = setTimeout(() => { signal?.removeEventListener('abort', abort); resolve(); }, ms);
      signal?.addEventListener('abort', abort, { once: true });
    });
  }
  function account(config) {
    const [first = '', second = ''] = String(config?.DATASYNC_ID || '').split('||');
    return { index: String(config?.SESSION_INDEX ?? '0'),
      delegated: config?.DELEGATED_SESSION_ID || (second ? first : ''),
      user: config?.USER_SESSION_ID || second || first };
  }
  function identity(config) {
    return JSON.stringify([account(config), config?.INNERTUBE_CONTEXT?.user?.onBehalfOfUser || '']);
  }
  function walk(value, visit) {
    if (!value || typeof value !== 'object') return;
    visit(value);
    for (const child of Object.values(value)) if (child && typeof child === 'object') walk(child, visit);
  }
  function parsePage(response, continuation = false) {
    if (!response || typeof response !== 'object' || response.error) {
      throw new Failure(response?.error?.message || 'Invalid playlist response.', 'response');
    }
    const alerts = (response.alerts || []).map(a => a.alertRenderer || a.alertWithButtonRenderer).filter(Boolean);
    if (alerts.some(a => a.type === 'ERROR')) throw new Failure('YouTube rejected the playlist request.', 'response');
    let items = null, owner = null;
    const containers = [];
    if (continuation) {
      const actions = [...(response.onResponseReceivedActions || []), ...(response.onResponseReceivedEndpoints || [])];
      for (const action of actions) if (action.appendContinuationItemsAction) containers.push({ owner: action.appendContinuationItemsAction, items: action.appendContinuationItemsAction.continuationItems });
      const list = response.continuationContents?.playlistVideoListContinuation;
      if (list) containers.push({ owner: list, items: list.contents });
    } else {
      walk(response.contents, obj => {
        if (obj.playlistVideoListRenderer) containers.push({ owner: obj.playlistVideoListRenderer, items: obj.playlistVideoListRenderer.contents });
      });
    }
    if (containers.length !== 1) throw new Failure('Ambiguous or missing playlist container.', 'schema');
    ({ items, owner } = containers[0]);
    if (!Array.isArray(items)) throw new Failure('Unrecognized playlist response; empty playlist not confirmed.', 'schema');
    const videos = [], tokens = [];
    if (owner.continuations != null) {
      if (!Array.isArray(owner.continuations)) throw new Failure('Invalid continuation metadata.', 'schema');
      for (const entry of owner.continuations) {
        const token = entry?.nextContinuationData?.continuation;
        if (typeof token !== 'string' || !token) throw new Failure('Unrecognized continuation metadata.', 'schema');
        tokens.push(token);
      }
    }
    for (const item of items) {
      const row = item.playlistVideoRenderer;
      if (row) {
        if (!row.setVideoId) throw new Failure('Playlist entry has no removal ID.', 'schema');
        const resume = row.thumbnailOverlays?.find(o => o.thumbnailOverlayResumePlaybackRenderer)?.thumbnailOverlayResumePlaybackRenderer;
        videos.push({ setVideoId: row.setVideoId, videoId: row.videoId || row.navigationEndpoint?.watchEndpoint?.videoId || null,
          watchedPercent: watchedPercent(resume?.percentDurationWatched ?? resume?.percentDurationWatchedString ?? 0) });
      } else if (item.continuationItemRenderer) {
        const local = [];
        walk(item.continuationItemRenderer, obj => { if (typeof obj.continuationCommand?.token === 'string' && obj.continuationCommand.token) local.push(obj.continuationCommand.token); });
        tokens.push(...local);
        if (!local.length) throw new Failure('Unrecognized continuation token.', 'schema');
      } else {
        // Unknown entries must not silently disappear from a deletion/verification scan.
        throw new Failure('Unrecognized playlist entry.', 'schema');
      }
    }
    if (new Set(tokens).size > 1) throw new Failure('Conflicting continuation tokens.', 'schema');
    return { videos, continuation: tokens[0] || null };
  }
  async function authHeaders(config, cookies, cryptoAPI = globalThis.crypto) {
    const jar = Object.fromEntries(cookies.split(';').map(c => {
      const [name, ...value] = c.trim().split('='); return [name, value.join('=')];
    }));
    const primary = jar.SAPISID || jar['__Secure-3PAPISID'];
    const schemes = [['SAPISIDHASH', primary], ['SAPISID1PHASH', jar['__Secure-1PAPISID']], ['SAPISID3PHASH', jar['__Secure-3PAPISID']]];
    const ts = Math.floor(Date.now() / 1000), parts = [], session = account(config);
    for (const [scheme, cookie] of schemes) {
      if (!cookie) continue;
      const input = `${session.user ? session.user + ' ' : ''}${ts} ${cookie} https://www.youtube.com`;
      const digest = await cryptoAPI.subtle.digest('SHA-1', new TextEncoder().encode(input));
      parts.push(`${scheme} ${ts}_${Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2, '0')).join('')}${session.user ? '_u' : ''}`);
    }
    if (!parts.length) throw new Failure('Authentication unavailable.', 'auth');
    const headers = { 'Content-Type': 'application/json', Authorization: parts.join(' '),
      'X-Goog-AuthUser': session.index, 'X-Origin': 'https://www.youtube.com' };
    if (session.delegated) headers['X-Goog-PageId'] = session.delegated;
    if (config.INNERTUBE_CONTEXT_CLIENT_NAME != null) headers['X-YouTube-Client-Name'] = String(config.INNERTUBE_CONTEXT_CLIENT_NAME);
    if (config.INNERTUBE_CONTEXT_CLIENT_VERSION) headers['X-YouTube-Client-Version'] = config.INNERTUBE_CONTEXT_CLIENT_VERSION;
    if (config.VISITOR_DATA) headers['X-Goog-Visitor-Id'] = config.VISITOR_DATA;
    return headers;
  }
  class Cleaner {
    constructor(adapter) {
      this.a = adapter; this.task = null; this.run = null; this.sequence = 0;
      this.state = { documentId: globalThis.crypto.randomUUID(), revision: 0, phase: 'idle', running: false, count: 0, observed: 0, remaining: null, total: null, matching: null, threshold: DEFAULT_THRESHOLD, message: 'Ready.' };
    }
    emit(update) {
      this.state = { ...this.state, ...update, revision: this.state.revision + 1 };
      try { this.a.onState?.({ ...this.state }); } catch (_) { /* Observers cannot interrupt a run. */ }
    }
    log(...args) { try { this.a.log?.(...args); } catch (_) {} }
    guard(run) {
      check(run.controller.signal);
      const currentConfig = run.identity ? this.a.config() : null;
      if (this.run !== run || !isWatchLater(this.a.url()) || (run.identity && (!currentConfig || identity(currentConfig) !== run.identity))) {
        run.controller.abort(); throw new Failure('Stopped: playlist or account changed.', 'cancelled');
      }
    }
    async ready(run) {
      for (let i = 0; i < 30; i++) {
        this.guard(run);
        const cfg = this.a.config();
        if (cfg?.INNERTUBE_CONTEXT && cfg?.INNERTUBE_API_KEY) { run.identity = identity(cfg); return cfg; }
        await delay(500, run.controller.signal);
      }
      throw new Failure('YouTube is still loading. Refresh the Watch Later page and try again.', 'config');
    }
    async request(run, endpoint, body) {
      this.guard(run);
      const cfg = this.a.config();
      const headers = await authHeaders(cfg, this.a.cookies());
      this.guard(run);
      const response = await this.a.request(`/youtubei/v1/${endpoint}?key=${encodeURIComponent(cfg.INNERTUBE_API_KEY)}&prettyPrint=false`,
        headers, { context: cfg.INNERTUBE_CONTEXT, ...body }, run.controller.signal);
      this.guard(run);
      if (!response || response.error) throw new Failure(response?.error?.message || 'Invalid API response.', 'response');
      return response;
    }
    async scan(run) {
      const videos = [], seenIDs = new Set(), seenTokens = new Set(); let token = null;
      for (let page = 0; page < 200; page++) {
        const result = parsePage(await this.request(run, 'browse', token ? { continuation: token } : { browseId: 'VLWL', params: 'wgYCCAA=' }), !!token);
        for (const video of result.videos) {
          if (!seenIDs.has(video.setVideoId)) { seenIDs.add(video.setVideoId); videos.push(video); }
        }
        if (!result.continuation) return videos;
        if (seenTokens.has(result.continuation)) throw new Failure('Playlist pagination repeated; scan incomplete.', 'pagination');
        seenTokens.add(result.continuation); token = result.continuation;
      }
      throw new Failure('Playlist scan limit reached; scan incomplete.', 'pagination');
    }
    async remove(run, batch) {
      let pending = batch;
      for (let attempt = 0; attempt < 2; attempt++) {
        this.guard(run);
        let result, failure;
        try {
          run.mutationPending = true;
          result = await this.request(run, 'browse/edit_playlist', { playlistId: 'WL', params: 'CAFAAQ==',
            actions: pending.map(v => ({ action: 'ACTION_REMOVE_VIDEO', setVideoId: v.setVideoId })) });
          if (result.status !== 'STATUS_SUCCEEDED') throw new Failure('YouTube rejected the batch edit.', 'edit');
          run.mutationPending = false;
          pending.forEach(v => run.removedIds.add(v.setVideoId));
          this.emit({ count: this.state.count + pending.length }); return;
        } catch (error) { failure = error; }
        this.guard(run);
        // A completed scan is the only valid way to infer absent IDs after an uncertain edit.
        const remaining = new Set((await this.scan(run)).map(v => v.setVideoId));
        pending.filter(v => !remaining.has(v.setVideoId)).forEach(v => run.removedIds.add(v.setVideoId));
        const stillPresent = pending.filter(v => remaining.has(v.setVideoId));
        this.emit({ count: this.state.count + pending.length - stillPresent.length });
        pending = stillPresent; run.mutationPending = false;
        if (!pending.length) return;
        if (attempt === 1) throw failure;
        await delay(1000, run.controller.signal);
      }
    }
    async execute(run) {
      await this.ready(run);
      let videos;
      try { videos = await this.scan(run); }
      catch (error) {
        this.guard(run);
        this.log('API scan failed', error.code, error.status, error.message);
        return this.fallback(run);
      }
      const targets = videos.filter(v => v.watchedPercent >= run.threshold);
      this.emit({ total: videos.length, remaining: videos.length, matching: targets.length, phase: 'removing', method: 'api' });
      for (let i = 0; i < targets.length; i += 100) {
        this.guard(run);
        this.emit({ message: `Removing videos… ${this.state.count} removed.` });
        try { await this.remove(run, targets.slice(i, i + 100)); }
        catch (error) {
          this.guard(run);
          // If verification itself failed, don't combine an unresolved edit with UI clicks.
          if (run.mutationPending) throw new Failure('Could not verify the last edit. Refresh before running again.', 'uncertain');
          this.log('Batch failed; UI fallback', error.code, error.message);
          return this.fallback(run, new Set(targets.slice(i).map(v => v.setVideoId).filter(id => !run.removedIds.has(id))));
        }
        await delay(350, run.controller.signal);
      }
      this.emit({ phase: 'verifying', message: 'Verifying the remaining playlist…' });
      const remaining = await this.scan(run);
      const selected = new Set(targets.map(v => v.setVideoId));
      const matching = remaining.filter(v => selected.has(v.setVideoId) || v.watchedPercent >= run.threshold).length;
      if (matching) throw new Failure(`${matching} matching videos remain. Run again to retry.`, 'partial');
      this.emit({ phase: 'done', remaining: remaining.length, message: `Done. Removed ${this.state.count}; ${remaining.length} kept.` });
    }
    async fallback(run, selectedIds = null) {
      this.guard(run);
      this.emit({ phase: 'fallback', method: 'ui', message: 'API unavailable. Using page controls; changes will be verified if possible.' });
      if (!this.a.fallback) throw new Failure('Page removal is unavailable.', 'fallback');
      const outcome = await this.a.fallback({ signal: run.controller.signal, threshold: run.threshold, selectedIds,
        onMutation: () => { this.guard(run); run.mutationPending = true; },
        guard: () => this.guard(run), onRemoved: () => this.emit({ observed: this.state.observed + 1 }) });
      this.guard(run);
      try {
        const remaining = await this.scan(run);
        const matching = remaining.filter(v => selectedIds?.has(v.setVideoId) || v.watchedPercent >= run.threshold).length;
        run.mutationPending = false;
        this.emit({ remaining: remaining.length });
        if (!matching) {
          this.emit({ phase: 'done', message: `Verified: no matching videos remain. ${remaining.length} kept.` }); return;
        }
      } catch (error) { this.guard(run); this.log('UI verification unavailable', error.message); }
      throw new Failure(`Page removal stopped: ${this.state.observed} rows removed, ${outcome.failed || 0} failed. Refresh to verify and retry.`, 'partial');
    }
    start(threshold = DEFAULT_THRESHOLD, options = {}) {
      if (this.task) return { accepted: false, message: 'The previous run is still stopping.', state: this.state };
      if (!isWatchLater(this.a.url())) return { accepted: false, message: 'Open your Watch Later playlist first.', state: this.state };
      const normalized = percent(threshold);
      if (normalized === 0 && !options?.confirmDeleteAll) {
        return { accepted: false, message: 'Removing everything requires confirmation. Pick a watched percentage above 0% or confirm deletion of the entire list.', state: this.state };
      }
      const run = { id: ++this.sequence, threshold: normalized, controller: new AbortController(), identity: null, mutationPending: false, removedIds: new Set() };
      this.run = run;
      this.emit({ runId: run.id, phase: 'scanning', running: true, count: 0, observed: 0, total: null, remaining: null,
        matching: null, threshold: run.threshold, startedAt: Date.now(), finishedAt: null, message: 'Scanning the playlist…', method: 'api', uncertain: false });
      // Schedule after task is assigned, so synchronous adapter failures cannot leave a stale task.
      this.task = Promise.resolve().then(() => this.execute(run)).catch(error => {
        const stopped = run.controller.signal.aborted || error.code === 'cancelled';
        this.log('Run ended', error.code, error.message);
        this.emit({ phase: stopped ? 'stopped' : 'error', uncertain: run.mutationPending,
          message: stopped ? `Stopped.${run.mutationPending ? ' An in-flight edit may have completed; refresh to verify.' : ''}` : error.message });
      }).finally(() => { this.emit({ running: false, finishedAt: Date.now() }); this.task = null; });
      return { accepted: true, state: { ...this.state } };
    }
    async stop() {
      if (this.task) {
        this.emit({ phase: 'stopping', message: 'Stopping…' }); this.run.controller.abort();
        await this.task;
      }
      return { accepted: true, state: { ...this.state } };
    }
  }
  const exports = { Cleaner, Failure, DEFAULT_THRESHOLD, percent, watchedPercent, isWatchLater, identity, parsePage, authHeaders, delay, check };
  if (typeof module !== 'undefined' && module.exports) module.exports = exports;
  else globalThis.WLCCore = exports;
})();

/* Firefox/console adapter. YouTube owns its DOM and internal list model. */
(() => {
  'use strict';
  if (globalThis.WatchLaterCleaner) return;
  const C = globalThis.WLCCore;
  const extension = typeof browser !== 'undefined' ? browser : null;
  const page = window.wrappedJSObject || window;
  const VERSION = extension?.runtime.getManifest().version || '3.0-console';
  const LAST_RUN_KEY = 'cleanerLastRun';
  let overlay = null, popupVisible = false, saving = Promise.resolve();
  const logs = [];
  function log(...args) {
    const message = args.map(v => String(v ?? '')).join(' ');
    logs.push({ time: Date.now(), message }); if (logs.length > 300) logs.shift();
    console.log('[WLC]', message);
  }
  function config() {
    try { return JSON.parse(JSON.stringify(page.ytcfg?.data_ || null)); }
    catch (_) { return null; }
  }
  async function request(path, headers, body, signal) {
    C.check(signal);
    const controller = new page.AbortController();
    const raw = { method: 'POST', headers, body: JSON.stringify(body), credentials: 'include' };
    const options = window.wrappedJSObject ? cloneInto(raw, page) : raw;
    options.signal = controller.signal;
    let timer, abort;
    const interrupted = new Promise((_, reject) => {
      abort = () => { controller.abort(); reject(new C.Failure('Stopped.', 'cancelled')); };
      signal.addEventListener('abort', abort, { once: true });
      timer = setTimeout(() => { controller.abort(); reject(new C.Failure('YouTube request timed out.', 'timeout')); }, 15000);
    });
    try {
      const operation = (async () => {
        const response = await page.fetch(new URL(path, 'https://www.youtube.com').href, options);
        const text = String(await response.text());
        if (response.status < 200 || response.status >= 300) throw new C.Failure(`YouTube API returned HTTP ${response.status}.`, 'http', response.status);
        try { return JSON.parse(text); }
        catch (_) { throw new C.Failure('YouTube returned invalid JSON.', 'json'); }
      })();
      return await Promise.race([operation, interrupted]);
    } finally { clearTimeout(timer); signal.removeEventListener('abort', abort); }
  }
  function makeOverlay() {
    if (overlay) return;
    const host = document.createElement('div');
    host.id = 'wlc-overlay-host';
    const shadow = host.attachShadow({ mode: 'closed' });
    shadow.innerHTML = `<style>
      :host { all:initial; position:fixed; bottom:20px; right:20px; z-index:2147483647; }
      section { max-width:340px; background:#181818; color:#fafafa; border:1px solid #555;
        border-radius:12px; padding:16px; font:14px/1.5 system-ui,sans-serif; box-shadow:0 4px 20px #0006; }
      p { margin:0 0 10px } button { cursor:pointer; padding:6px 12px; margin-right:8px; }
    </style><section aria-live="polite"><p></p><button id="stop">Stop</button><button id="refresh">Refresh playlist</button><button id="close">Dismiss</button></section>`;
    overlay = { host, text: shadow.querySelector('p'), stop: shadow.querySelector('#stop'), refresh: shadow.querySelector('#refresh') };
    overlay.stop.addEventListener('click', () => cleaner.stop());
    overlay.refresh.addEventListener('click', () => { if (!cleaner.state.running && C.isWatchLater(location.href)) location.reload(); });
    shadow.querySelector('#close').addEventListener('click', () => { if (!cleaner.state.running) { host.remove(); overlay = null; } });
    (document.body || document.documentElement).appendChild(host);
  }
  function render(state) {
    if (state.phase === 'idle') return;
    makeOverlay();
    overlay.host.style.display = popupVisible ? 'none' : 'block';
    overlay.text.textContent = `${state.message}${state.running ? ` Confirmed API removals: ${state.count}; UI rows removed: ${state.observed}.` : ''}`;
    overlay.stop.hidden = !state.running; overlay.stop.disabled = state.phase === 'stopping';
    overlay.refresh.hidden = state.running;
  }
  function saveRun(state) {
    if (!extension || state.running || !state.runId) return;
    const snapshot = { version: VERSION, state: { ...state }, logs: logs.slice(), savedAt: Date.now() };
    saving = saving.catch(() => {}).then(() => extension.storage.local.set({ [LAST_RUN_KEY]: snapshot }));
    saving.catch(error => log('Could not save diagnostics:', error.message));
  }
  function rowInfo(row) {
    // Unwrap only to read the row's action identity; never write page-model objects.
    let data;
    try { const raw = row.wrappedJSObject || row; data = JSON.parse(JSON.stringify(raw.data || raw.__data?.data || null)); } catch (_) {}
    const href = row.querySelector('a#video-title[href], a#thumbnail[href]')?.href;
    let videoId = data?.videoId || null;
    try { videoId ||= new URL(href).searchParams.get('v'); } catch (_) {}
    const progress = row.querySelector('ytd-thumbnail-overlay-resume-playback-renderer #progress');
    const match = (progress?.style.width || '').match(/([\d.]+)%/);
    const key = data?.setVideoId || videoId || row;
    return { key, setVideoId: data?.setVideoId || null, videoId, watchedPercent: C.watchedPercent(match?.[1] || 0) };
  }
  function menuData(node) {
    try { const raw = node.wrappedJSObject || node; return JSON.parse(JSON.stringify(raw.data || raw.__data?.data || null)); } catch (_) { return null; }
  }
  function removalMatches(data, info) {
    if (!data || typeof data !== 'object') return false;
    const endpoint = data.serviceEndpoint?.playlistEditEndpoint || data.navigationEndpoint?.playlistEditEndpoint || data.playlistEditEndpoint;
    return endpoint?.playlistId === 'WL' && Array.isArray(endpoint.actions) && endpoint.actions.length === 1 && endpoint.actions.every(a => a.action === 'ACTION_REMOVE_VIDEO'
      && ((info.setVideoId && a.setVideoId === info.setVideoId) || (!a.setVideoId && info.videoId && a.removedVideoId === info.videoId)));
  }
  function visible(node) { return !!(node && node.getClientRects().length && getComputedStyle(node).visibility !== 'hidden'); }
  async function until(test, control, ms = 3000) {
    for (let elapsed = 0; elapsed < ms; elapsed += 100) {
      control.guard(); const value = test(); if (value) return value;
      await C.delay(100, control.signal);
    }
    return null;
  }
  async function removeRow(row, info, control) {
    control.guard();
    const button = row.querySelector('#menu button'); if (!button) return false;
    // Close old menus before opening this row's menu.
    document.body.click();
    await C.delay(100, control.signal); control.guard();
    if (!row.isConnected) return false;
    button.click();
    const option = await until(() => {
      for (const menu of document.querySelectorAll('ytd-menu-popup-renderer')) {
        if (!visible(menu)) continue;
        for (const item of menu.querySelectorAll('ytd-menu-service-item-renderer, [role="menuitem"]')) {
          if (visible(item) && removalMatches(menuData(item), info)) return item;
        }
      }
      return null;
    }, control);
    control.guard();
    if (!option || !row.isConnected) { document.body.click(); return false; }
    control.onMutation();
    option.click();
    const gone = await until(() => !row.isConnected, control, 5000);
    if (!gone) { document.body.click(); throw new C.Failure('Page removal outcome is unknown. Refresh to verify.', 'uncertain'); }
    return !!gone;
  }
  async function fallback(control) {
    let failed = 0, idle = 0; const processed = new Set();
    while (idle < 5) {
      control.guard();
      const rows = [...document.querySelectorAll('ytd-playlist-video-renderer')];
      const next = rows.map(row => ({ row, info: rowInfo(row) })).find(v => !processed.has(v.info.key));
      if (next) {
        idle = 0; processed.add(next.info.key);
        if (control.selectedIds ? !control.selectedIds.has(next.info.setVideoId) : next.info.watchedPercent < control.threshold) continue;
        next.row.scrollIntoView({ block: 'center' });
        await C.delay(150, control.signal); control.guard();
        if (await removeRow(next.row, next.info, control)) control.onRemoved(); else failed++;
        await C.delay(400, control.signal); continue;
      }
      const before = rows.length;
      rows.at(-1)?.scrollIntoView({ block: 'end' });
      window.scrollBy(0, Math.max(600, window.innerHeight));
      await C.delay(1500, control.signal); control.guard();
      if (document.querySelectorAll('ytd-playlist-video-renderer').length > before) idle = 0; else idle++;
    }
    // The core verifies via a full API scan; DOM exhaustion alone never proves completion.
    return { failed, incomplete: false };
  }
  const cleaner = new C.Cleaner({ url: () => location.href, config, cookies: () => document.cookie, request, fallback, log,
    onState: state => { render(state); saveRun(state); extension?.runtime.sendMessage({ type: 'state', state }).catch(() => {}); } });
  globalThis.WatchLaterCleaner = cleaner;
  let previewController = null;
  async function estimate(threshold) {
    if (cleaner.state.running) throw new C.Failure('Cleaning is running.', 'busy');
    previewController?.abort();
    const preview = new C.Cleaner({ url: () => location.href, config, cookies: () => document.cookie, request });
    const run = { controller: new AbortController(), identity: null };
    previewController = run.controller; preview.run = run;
    await preview.ready(run);
    const videos = await preview.scan(run);
    return { total: videos.length, matching: videos.filter(v => v.watchedPercent >= C.percent(threshold)).length };
  }
  async function diagnostics() {
    await saving.catch(() => {});
    if (cleaner.state.runId) return { version: VERSION, state: cleaner.state, logs: logs.slice() };
    return extension ? (await extension.storage.local.get(LAST_RUN_KEY))[LAST_RUN_KEY] || null : null;
  }
  if (extension) {
    extension.runtime.onMessage.addListener(message => {
      switch (message.command) {
        case 'status': return Promise.resolve({ ...cleaner.state });
        case 'start': previewController?.abort(); return Promise.resolve(cleaner.start(message.threshold, { confirmDeleteAll: message.confirmDeleteAll }));
        case 'estimate': return estimate(message.threshold);
        case 'stop': return cleaner.stop();
        case 'getLogs': return diagnostics();
        case 'setPopupVisible':
          popupVisible = !!message.visible;
          if (!popupVisible) previewController?.abort();
          render(cleaner.state); return Promise.resolve({ ok: true });
        default: return undefined;
      }
    });
  }
  function navigation() {
    if (!cleaner.state.running) return;
    try { cleaner.guard(cleaner.run); } catch (_) { cleaner.stop(); }
  }
  document.addEventListener('yt-navigate-start', () => { previewController?.abort(); if (cleaner.state.running) cleaner.stop(); });
  document.addEventListener('yt-navigate-finish', navigation);
  window.addEventListener('popstate', navigation);
  window.addEventListener('pagehide', () => { if (cleaner.state.running) cleaner.stop(); });
  // Also catches account changes that do not emit a YouTube navigation event.
  setInterval(navigation, 500);
  log(`Loaded v${VERSION}`);
})();

WatchLaterCleaner.start(0, { confirmDeleteAll: true });
